/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.*;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
/**
 *
 * @author daze
 */
public class MainFrame extends javax.swing.JFrame {

    
//	public static JButton btnSend = new JButton("send");
//	public static JTextField messageContent;
//	public static JTextArea messageFrom;
//	public static JComboBox<String> comboBox;
    
    public  javax.swing.JButton btnSend;
    public  javax.swing.JButton btnSendFile;
    public  javax.swing.JComboBox<String> comboBox;
    public  javax.swing.JButton emoji;
    private javax.swing.JButton getUserList;
    public  javax.swing.JList<String> jList1;
    public  javax.swing.JMenu jMenu1;
    public  javax.swing.JMenu jMenu2;
    public  javax.swing.JMenuBar jMenuBar1;
    public  javax.swing.JScrollPane jScrollPane1;
    public  javax.swing.JScrollPane jScrollPane2;
    public  javax.swing.JScrollPane jScrollPane3;
    public  javax.swing.JScrollPane jScrollPane4;
    public  javax.swing.JTabbedPane jTabbedPane1;
    public  javax.swing.JTextArea jTextArea3;
    public  javax.swing.JTextArea messageContent;
    public  javax.swing.JTextArea messageFrom;
    
	private Socket s1 = null;
	public static int PortOfFileTrans = 8888;
	
	private DataInputStream dis = null;
	private DataOutputStream dos = null;
	
	protected String name;
       
	private FriendStatus friendsList;
	
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageFrom = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        btnSendFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        comboBox = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageContent = new javax.swing.JTextArea();
        emoji = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        getUserList = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(50, 23));

        messageFrom.setColumns(20);
        messageFrom.setRows(5);
        jScrollPane3.setViewportView(messageFrom);

        jTabbedPane1.addTab("namelabel", jScrollPane3);

        jScrollPane4.setMinimumSize(new java.awt.Dimension(50, 23));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jTabbedPane1.addTab("namelabel", jScrollPane4);

        btnSendFile.setText("send File");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        messageContent.setColumns(20);
        messageContent.setRows(5);
        jScrollPane2.setViewportView(messageContent);

        emoji.setText("emoji");
        emoji.setToolTipText("");

        btnSend.setText("send");

        getUserList.setText("friend");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getUserList, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emoji, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jTabbedPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(comboBox, 0, 176, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(btnSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emoji, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(getUserList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */


public MainFrame(Socket s, String name) {
		
		this.s1 = s;
		this.name = name;
		initComponents();
		MainFrame.this.setTitle(name);
		
		ReceiveMessageThread userReceiveMessageThread = new ReceiveMessageThread(s1, MainFrame.this, name);
		userReceiveMessageThread.start();
		
		try {
			dis = new DataInputStream(s1.getInputStream());
			dos = new DataOutputStream(s1.getOutputStream());
			
			dos.writeUTF("102|");
			System.out.println(name + " send 102");
			dos.flush();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
        MainFrame.this.setVisible(true);
           
		btnSend.addActionListener(new btnSendListener());
		btnSendFile.addActionListener(new btnSendFileListener());
		getUserList.addActionListener(new getUserListListener());
		
		friendsList = new FriendStatus(MainFrame.this);
 	}

	
	class getUserListListener implements ActionListener{

		@Override
		public void actionPerformed(ActionEvent e) {
			try {
				dis = new DataInputStream(s1.getInputStream());
				dos = new DataOutputStream(s1.getOutputStream());
				
				dos.writeUTF("102|");
				System.out.println(name + " send 102");
				dos.flush();
			} catch (IOException e1) {
				e1.printStackTrace();
			}
		}
		
	}

	class btnSendListener implements ActionListener{
		  public void actionPerformed(ActionEvent e) {

			  	//System.out.println("send message");
						/*
						 * make a communication protocol between server and client
						 * 
						 * 101|name, pass -- login to server
						 * 102| 		   --ask server for user list
						 * 103|from, to, message -- talk to other user
						 * 
						 */
						
						String from = MainFrame.this.name;
						String to = MainFrame.this.comboBox.getSelectedItem().toString();
						String content = MainFrame.this.messageContent.getText();
						String time = new Date().toString();
						
						try {
							//dis = new DataInputStream(s.getInputStream());
							//dos = new DataOutputStream(s.getOutputStream());
							if (!to.equals("allUser")) {
								dos.writeUTF("103|" + from + "," + to + "," + content);
								MainFrame.this.messageFrom.append("(" + time + ") to " + to +  " :\r\n"+ content + "\r\n");
								MainFrame.this.messageContent.setText(null);
								dos.flush();
							} else {
								//to.equals("allUser")
								
								ArrayList<Userinfo> userList = friendsList.getFriendList();
								friendsList.printFriendList();
								
								for (int i = 0; i < userList.size(); i++) {
									
									Userinfo u = userList.get(i);
									if (!u.getName().equals(from) || !u.getName().equals("allUser")) {
										to = u.getName();
										dos.writeUTF("103|" + from + "," + to + "," + content);
										dos.flush();
									}
									
									try {
										Thread.sleep(1000);
									} catch (InterruptedException e1) {
										e1.printStackTrace();
									}
									
									
								}
							}
							
						} catch (IOException e1) {
							e1.printStackTrace();
						}
						
					
				}
		}
	
	class btnSendFileListener implements ActionListener {
		public void actionPerformed(ActionEvent arg0) {
			JFileChooser addChooser = new JFileChooser(); 
			String from = MainFrame.this.name;
			String to = MainFrame.this.comboBox.getSelectedItem().toString();
            addChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES); 
            
            //enable MultiSelection to choose more than one files
            addChooser.setMultiSelectionEnabled(true); 
            
            int returnval = addChooser.showOpenDialog(MainFrame.this);   
            if(returnval == JFileChooser.APPROVE_OPTION) 
            { 
                File[] files = addChooser.getSelectedFiles(); 
                String str = ""; 
                for (File file : files) { 
                	try {
						dos.writeUTF("104|" + from + "," + to + "," + file.getName());
						dos.flush();
						new FileSendThread(file, MainFrame.this.s1).start();							
					} catch (IOException e) {
						e.printStackTrace();
					}                       
                } 
            }
		}
	}
}



/*
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendFile;
    public javax.swing.JComboBox<String> comboBox;
    private javax.swing.JButton emoji;
    private javax.swing.JButton getUserList;
    public javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea messageContent;
    private javax.swing.JTextArea messageFrom;
    // End of variables declaration                   

*/